### ISSUE TITLE
Tags separated from headline text by \t not recognized

### ISSUE THREAD

**Issue by calmofthestorm** [PoiScript/orgize#15]
This is a fairly minor issue, but it does differ from org-mode's behavior. My read of the spec is completely ambiguous on this point -- it explicitly specifies (and org will only recognize) that the *** of the headline MUST end with a "space", but org-mode seems to accept \t and possibly other exotic whitespace (untested) for separating the tags from the rest of the headline.

I'm going to file this since I noticed it, but I can also see the argument that this is working as intended.

**Comment by PoiScript** [comment]
Fixed by v0.8.3.
