### ISSUE TITLE
Cannot parse empty headlines with tags

### ISSUE THREAD

**Issue by calmofthestorm** [PoiScript/orgize#17]
It looks like empty headlines' tags get treated as part of the raw, and the tags not picked up.

```
fn main() {
    let org = orgize::Org::parse("* :a:");
    assert_eq!(vec!("a"), org.headlines().next().unwrap().title(&org).tags);
}
```

**Comment by PoiScript** [comment]
Yes, this is the expected behavior of org-elements api:

<img width="737" alt="Screen Shot 2020-05-06 at 10 22 13 AM" src="https://user-images.githubusercontent.com/17513314/81133184-7682e900-8f83-11ea-87e6-82ddc4c43594.png">

**Comment by calmofthestorm** [comment]
It looks like org mode itself also has this behavior, so my understanding of the spec was incorrect. Thanks for checking.

**Comment by PoiScript** [comment]
Actually, the [org syntax](https://orgmode.org/worg/dev/org-syntax.html) is quite brief. It doesn't cover every possible edge cases like [CommonMark does](https://spec.commonmark.org/). So orgize will try to behave the same way as org-elements api (the builtin org-mode parser), and may not follow the [org syntax](https://orgmode.org/worg/dev/org-syntax.html) in some situations.

**Comment by calmofthestorm** [comment]
Thanks for the explanation. I agree it makes sense to try to track org-mode/org-elements as closely as possible, given that if they and the standard disagree, I suspect the standard is more likely to be updated than they are unless it's an important failure mode.
