### ISSUE TITLE
Orgize does not produce html image tags for image links

### ISSUE THREAD

**Issue by JWorthe** [PoiScript/orgize#37]
Good evening! Thank you for writing and maintaining this library. I think it's great to have a Rust library that can render Org-mode to html.

Some unexpected behaviour I've run into is that `DefaultHtmlHandler` doesn't render images. I think it's because images aren't actually mentioned in the spec, but are rather a special case for links to files with certain extensions.

For example, `[[org-mode-unicorn.png]]` should render to `<img src="org-mode-unicorn.png" />` rather than an `<a>` tag because of the png extension.

This page describes how I would expect the default behaviour to be: https://orgmode.org/worg/org-tutorials/images-and-xhtml-export.html

**Comment by PoiScript** [comment]
Image link is now supported in v0.10:

<img width="1159" alt="image" src="https://github.com/PoiScript/orgize/assets/17513314/5d76189e-d266-4fb6-9687-c8252ab21443">
