### ISSUE TITLE
Handle LaTeX fragments and environments — $x!$, $$y$$, \begin{equation}z\end{equation}

### ISSUE THREAD

**Issue by holtzermann17** [PoiScript/orgize#42]
This is a ticket to track progress on LaTeX fragments and environments, to be added per
- https://github.com/PoiScript/orgize/blob/e009e1c199d78e2531bed1913a6e40a0f167c2d5/docs/STATUS.md#L43
- https://github.com/PoiScript/orgize/blob/e009e1c199d78e2531bed1913a6e40a0f167c2d5/docs/STATUS.md#L36

https://github.com/PoiScript/orgize/blob/e009e1c199d78e2531bed1913a6e40a0f167c2d5/src/parsers.rs#L291 looks like the start of a handler for `\` tokens.

This is of interest to downstream consumers, like Firn (https://github.com/theiceshelf/firn/issues/56).

**Comment by PoiScript** [comment]
latex support is introduced in `v0.10.0-alpha.3`.
