### ISSUE TITLE
Support for org-entities (special symbols)

### ISSUE THREAD

**Issue by lyderichti59** [PoiScript/orgize#44]
Hi,

I use [Firn](https://github.com/theiceshelf/firn), a static site generator, that depends on Orgize. I want to use [org-mode's special symbols](https://orgmode.org/manual/Special-Symbols.html) in my org files, and produce the expected HTML ( with non breaking spaces and narrow no-break spaces for the moment, but I may need many other special symbols too). 

When I use the [live demo](https://orgize.herokuapp.com/),
And input this : `Hello\nbsp{}world`
I get this : 
```{"type":"document","children":[{"type":"section","children":[{"type":"paragraph","children":[{"type":"text","value":"Hello\\nbsp{}world"}]}]}]}```

Special symbols are parsed as plain text in the generated json.

Do you think that a support for org-entities is doable, or should it be done directly in the client code ?

**Comment by PoiScript** [comment]
org entity support is introduced in orgize `v0.10.0-alpha.3`.
