### ISSUE TITLE
Incomplete Syntax: No definition list support

### ISSUE THREAD

**Issue by Atlas48** [PoiScript/orgize#63]
By default, org-mode includes a [definition list](https://orgmode.org/manual/Plain-Lists.html), this doesn't appear to be accounted for when making a list, so the parsing included in this library is incomplete.

definition lists are made by the following syntax

```
- Hello :: World
```

**Comment by PoiScript** [comment]
I assume you meant the description list, description list is now supported in v0.10:

<img width="1387" alt="image" src="https://github.com/PoiScript/orgize/assets/17513314/e478e47b-4de5-4c47-bd25-013b6c5d6a4b">
