### ISSUE TITLE
symlinks break builds under Nix

### ISSUE THREAD

**Issue by gmemstr** [PoiScript/orgize#73]
When building this package with a crate using a Nix Flake, the symlink introduced in 4cc1130a175121fda2136ede9bccefd7e228388b appears to break the build - why specifically I'm not sure, but it's likely because the symlink is outside of the crates source directory.

This could be fixed by either removing the file or, more likely, making it a "real" file.

**Comment by PoiScript** [comment]
symlinks have been removed
